### PR TITLE
User Login/Logout/Etc...

### PR DESCRIPTION
**Pull request by DarthHater**
This is the start of the User session stuff.

So far if you do:

POST: http://localhost:8000/login
BODY:
`
{
	"username": "CoolAssMitch420",
	"password": "coolassmitch420"
}
`

You should get a 200 and an "OK" response.

With:
`
{
	"username": "CoolAssMitch420",
	"password": "bad"
}
`

You'll get a 401 and an error response.

If you do:
POST:http://localhost:8000/register
BODY:
`
{
	"username": "NewUser311",
	"emailaddress": "311Rules@311fanclub.com",
	"userpassword": "comeoriginal"
}
`

You should then be able to do:

POST: http://localhost:8000/login
BODY:
`
{
	"username": "NewUser311",
	"password": "comeoriginal"
}
`

As well, a new endpoint for logout exists:
GET: http://localhost:8000/protected/:username

This will first check if the user has a session (make sure logout isn't being called maliciously), then clear any details on their session. Returns a 400 if unsuccessful.

TODO:
- [x] Create new session on successful login
- [x] Implement a logout() endpoint
- [x] Implement a register() endpoint
- [ ] Sanitize error messages

### CODE REVIEW

**Comment by andysbolton** [comment]
Hey, I'd love to contribute if possible but it looks like most of these are finished. Are there any other tasks to do at the moment or do you mostly have it taken care of?

**Comment by DarthHater** [comment]
@andysbolton dude, awesome! Uh, this is kinda WIP and an experiment to be honest. A different tact you could take is to do this same thing with JWT. The more I'm reading the more I think that JWT might be better, because it would allow the site to be accessed from not only SPA but also a native app if someone wanted to make one. I'll add you as a collaborator on the project so you can spin a branch here (easier for everyone). That sound ok?

**Comment by DarthHater** [comment]
Also I'll see if I can be a bit better about creating issues so it's easier to see what someone could pick off. Been kinda heads down working on my own so I didn't take much time to do so.

**Comment by andysbolton** [comment]
Yeah, that sounds great! I've used JWT on one other project so will so if I can get something going here.

**Comment by DarthHater** [comment]
You should be able to lift quite a bit from this PR @andysbolton , the generic endpoints and how we get stuff from the database would be easy to steal unless you think I've done it catastrophically wrong (which is fine to point out, btw). I think the stuff that ends up changing is killing all the session stuff and just doing it with JWT? I dunno, never done it, but have a blast.

**Comment by andysbolton** [comment]
Okay, awesome, I'll go ahead and make a branch and do some experimenting.

**Pull request closed without merging**
