### PR TITLE
Edit posts

### PR DESCRIPTION
**Pull request by andysbolton**
This creates an endpoint to edit posts within 10 minutes of them being posted. For whatever reason I could not get `fresh` to work for me, so I replaced it with [realize](https://github.com/oxequa/realize). It should function largely the same as `fresh` but if there are any downsides or anything please let me know and I'll switch it out. 

Also added an environmental variable for remote debugging so you can build the docker container with debugging or with code rebuilding/restarting.

### CODE REVIEW

**Comment by DarthHater** [comment]
Not ignoring this, been really busy with some life stuff. I'll get to reviewing it and merging it hopefully next week, thanks @andysbolton , appreciate you digging in to this!

**Comment by DarthHater** [comment]
Also, stoked on you introducing realize, had not seen that and I'm glad to play with it.

**Comment by andysbolton** [comment]
Sweet, no worries, I've been pretty busy too lately, should have some more time coming up pretty soon though.

**Comment by DarthHater** [comment]
Man, I have been SUPER busy and just kinda off the radar. Getting back around to this. Heads up, I've made some big changes on master as I get the app running on Heroku (I got a wild hair today and figured I'd get it running) so make sure to watch those @andysbolton !

**Comment by andysbolton** [comment]
Awesome @DarthHater, looking forward to it!

**Comment by DarthHater** [comment]
Got it running, albeit with some less than stellar hacks. The new travis ci stuff deploys to heroku container registry and releases, I need to switch it to only do that on master, but it's kinda up and running now:

https://vivalavinyl.herokuapp.com/threads

Get in touch with your email address and I can add you to the heroku stuff if you'd like.

**Comment by andysbolton** [comment]
Cool. My email address is andy.s.bolton@gmail.com.

**Comment by andysbolton** [comment]
@DarthHater I think I'm gonna close this PR and start up a new one with a branch that has some additional changes in it.

**Pull request closed without merging**
